### PR TITLE
Pin versions of dependencies Indy Node and Plenum.

### LINKED ISSUE #2317: Docker-compose up: Service 'indy_pool' failed to build
Trying to follow the "Indy Getting Started" guide, I face issues running ``docker-compose up`` in ``/indy-sdk/docs/getting started`` that seem to be rooting from indy-plenum (ci/indy-pool.dockerfile line28 following). An extract of the terminal can be found below. 
Problems came up on Ubuntu 18.04, 16.04 and 20.04 VMs. Two colleagues of mine face the same issue, so it should'nt be a local problem. 
Does anyone know how to fix this? I hope this is the right place to ask, thank you in advance for your help.

```
Step 14/22 : RUN apt-get update -y && apt-get install -y python3-pyzmq=${python3_pyzmq_ver} indy-plenum=${indy_plenum_ver} indy-node=${indy_node_ver} python3-indy-crypto=${python3_indy_crypto_ver} libindy-crypto=${indy_crypto_ver} vim
---> Running in bdb382729991
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [2376 kB]
Get:6 https://repo.sovrin.org/deb xenial InRelease [28.4 kB]
Get:7 https://repo.sovrin.org/deb xenial/master amd64 Packages [345 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [1855 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [1527 kB]
Fetched 6457 kB in 5s (1139 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
indy-plenum : Depends: python3-orderedset (= 2.0) but 2.0.3 is to be installed
Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
Depends: python3-pympler (= 0.5) but 0.8 is to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'indy_pool' failed to build: The command '/bin/sh -c apt-get update -y && apt-get install -y python3-pyzmq=${python3_pyzmq_ver} indy-plenum=${indy_plenum_ver} indy-node=${indy_node_ver} python3-indy-crypto=${python3_indy_crypto_ver} libindy-crypto=${indy_crypto_ver} vim' returned a non-zero code: 100 
```

### PR DESCRIPTION
**Pull request by jovfer**
Fixes #2317

### CODE REVIEW

**Comment by WadeBarnes** [comment]
The Windows tests are failing in the same way they are failing in PR https://github.com/hyperledger/indy-sdk/pull/2328.

**Comment by WadeBarnes** [comment]
This PR is patching the `ci/indy-pool.dockerfile` as discussed in Issue https://github.com/hyperledger/indy-sdk/issues/2317.  Where PR https://github.com/hyperledger/indy-sdk/pull/2328 makes an attempt at upgrading the `indy-plenum` and `indy-node` versions in order to resolve the dependency issues.

**Comment by jovfer** [comment]
@WadeBarnes I've re-run this PR on Jenkins with trace level and can see the following:
at one of the test the libindy can successfully do a catch-up 
but the next one write request is failed: the library receives all ACKs, but no replies at all and we will have final timeout and failure
https://build.sovrin.org/job/indy-sdk/job/indy-sdk-ci/job/PR-2330/3/console here you can find trace, the most interesting part of the logs starts at line `test high_cases::cred_def_cache::indy_get_cred_def_cache_works`

I can see next step is to pause the pipeline after the first failure and go and check the help of the test pool. Either it crashes now for some dependency reason or due to env issues like out of disk space.
Usually such behavior (all acks but no replies) means hard fault of the pool and rebooting it

**Comment by WadeBarnes** [comment]
https://github.com/hyperledger/indy-sdk/pull/2328#issuecomment-748510131

**Review by WadeBarnes — COMMENTED** [review]
Although this works, my preference is to upgrade the `indy-plenum` and `indy-node` versions in order to resolve the dependency issues, as was done in PR https://github.com/hyperledger/indy-sdk/pull/2328

**Comment by jovfer** [comment]
@WadeBarnes well, I see the value in #2328 (bump the nodes version), but I have a couple of question about it, so I suggest to merge this PR and unblock CI/CD and then merge 2328 after some minor clean-up

**Review by Toktar — APPROVED** [review]

**Pull request merged**
