### PR TITLE
Getting Started Guide for farskipper's node.js wrapper

### PR DESCRIPTION
**Pull request by saholman**
This is a simple getting started guide, based on the existing python getting started guide, that uses farskipper's node.js wrapper. See https://github.com/hyperledger/indy-sdk/pull/616.  After farskipper's pull request is merged, I can change the package.json to pull from the file rather than from the npm registry.

### CODE REVIEW

**Comment by saholman** [comment]
@vimmerru How can I add the DCO to the first commit?  I tried `git rebase --exec 'git commit --amend --no-edit -n --signoff' -i master` but it is still failing the DCO sign-off.

**Comment by saholman** [comment]
@jovfer What still needs to be done before this can be merged into the master branch?

**Comment by vimmerru** [comment]
@saholman I suggest to merge NodeJS CI pipeline first(we plan to merge it soon). Main problem is supporting of this code in the future and checking of correctness as part of our CI

**Comment by jovfer** [comment]
Moved to #834

**Pull request closed without merging**
