### PR TITLE
How-tos refactor

### PR DESCRIPTION
**Pull request by r0qs**
Hello, I noticed that the how-tos documentation has many duplicated information with small differences between each wrapper language, which can make difficulty the maintenance of the documentation. So in this pull-request, I'm proposing a new structure for the how-tos docs, starting with the "write-did-and-query-verkey". 

The idea is to have only one point of information about each how-to and links for the different implementations on each step.

I would like to know what do you think about it, and if I can continue to make this changes in the rest of the documentation or what could be improved to allow a more up to date documentation for the project.

### CODE REVIEW

**Comment by dhh1128** [comment]
This seems like a good idea in theory. However, I think importing from various directory paths makes python code a bit ugly, so I am wondering if we'd be better off using hard links instead--that is, make the same file (e.g., Step1.cs) be hard linked to several places in the directory tree, instead of stored in a single common location.

I am not super strong on this idea; I'm just wondering aloud if this would be better. Feel free to push back.

**Comment by r0qs** [comment]
@dhh1128, maybe I wasn't clear when I said about the links for different implementations, I'm not referring to change any line of code in the examples, just the location of the documents (readme files mainly).

The current structure of the write-did-and-query-verkey example is this:
```
write-did-and-query-verkey
├── cs
│   ├── Program.cs
│   ├── README.md
│   ├── step2.partial
│   ├── step3.partial
│   ├── step4.partial
│   ├── step5.partial
│   ├── template.cs
│   └── write-did-and-query-verkey.csproj
├── java
│   ├── README.md
│   ├── step2.java
│   ├── step3.java
│   ├── step4.java
│   ├── step5.java
│   ├── template.java
│   └── WriteDIDAndQueryVerkey.java
├── nodejs
│   ├── colors.js
│   ├── package.json
│   ├── README.md
│   ├── step2.js
│   ├── step3.js
│   ├── step4.js
│   ├── step5.js
│   ├── template.js
│   ├── util.js
│   └── writeDidAndQueryVerkey.js
├── python
│   ├── extra
│   │   └── add_nym.py
│   ├── README.md
│   ├── step2.py
│   ├── step3.py
│   ├── step4.py
│   ├── step5.py
│   ├── template.py
│   └── write_did_and_query_verkey.py
├── README.md
├── rust
│   ├── Cargo.toml
│   ├── README.md
│   └── src
│       ├── step2.rs
│       ├── step3.rs
│       ├── step4.rs
│       ├── step5.rs
│       ├── template.rs
│       └── write-did-and-query-verkey.rs
└── wallet-slide.png
```
And as you can see there is a readme file for every code sample that are basically copies of each other, which can be error prone, as you can notice [here](https://github.com/hyperledger/indy-sdk/tree/master/docs/how-tos/negotiate-proof/nodejs#step-1), where someone probably copied the step1 from the python example, but forgot to change ` a python editor` to `a javascript editor`.

My idea is to reduce the probability to this kind of errors occur, making this structure:
```
write-did-and-query-verkey
├── cs
│   ├── Program.cs
│   ├── Template.cs
│   ├── WriteDIDAndQueryVerkey.cs
│   └── write-did-and-query-verkey.csproj
├── java
│   ├── step2.java
│   ├── step3.java
│   ├── step4.java
│   ├── step5.java
│   ├── template.java
│   └── WriteDIDAndQueryVerkey.java
├── nodejs
│   ├── colors.js
│   ├── package.json
│   ├── step2.js
│   ├── step3.js
│   ├── step4.js
│   ├── step5.js
│   ├── template.js
│   ├── util.js
│   └── writeDidAndQueryVerkey.js
├── python
│   ├── extra
│   │   └── add_nym.py
│   ├── step2.py
│   ├── step3.py
│   ├── step4.py
│   ├── step5.py
│   ├── template.py
│   └── write_did_and_query_verkey.py
├── README.md
├── rust
│   ├── Cargo.toml
│   └── src
│       ├── step2.rs
│       ├── step3.rs
│       ├── step4.rs
│       ├── step5.rs
│       ├── template.rs
│       └── write-did-and-query-verkey.rs
└── wallet-slide.png
```

Here, you only have one readme file that describe the example scenario, independent of the programming language chosen by the reader, since all the examples describe the same scenario and only the code changes.

**Comment by dhh1128** [comment]
Ah yes, you're right--I misunderstood. I was focused on a different problem, which is that often step X of a given how-to is identical to step X of a different how-to. For example, the first few steps of the how-to for issuing credentials are identical to the steps in the "write a DID to the ledger" how-to. We can solve that problem with relative hyperlinks. The problem you're solving is different, and I like your solution. So +1 from me.

**Comment by johncallahan** [comment]
I've been refactoring the rust how-tos lately ([1536 - Save Schema](https://github.com/hyperledger/indy-sdk/pull/1536), [1565 - Issue Credential](https://github.com/hyperledger/indy-sdk/pull/1565)) with two more to go (Proof Verification and Secure Messaging - I'm already done, but I'm submitting one PR at a time).   These examples have proved invaluable to me understanding the whole indy-sdk API (wallet, ledger, etc.)

In each case, I built a Rust project with separate "cargo new <name> --bin" project and used src/main.rs and a working Cargo.toml file to make sure the how-to example actually works.  While I understand the step2.rs, step3.rs, etc. process, it seems we could improve the pain factor for newbies.  At least on the rust examples.

**Comment by r0qs** [comment]
Hi @dhh1128, I think that I finished, below is a summary of my tests, if there are something that need to be fixed, please let me know. I didn't fix the rust example, since @johncallahan already did in other PRs. I'll also try to finish the nodejs examples, but I think that for now is better to do that in other PRs changing only the code and applying the relative hyperlinks approach that you suggested.

I = Implemented and tested
F = Implemented, but fail or wasn't tested by me
N = Not implemented or incomplete

| How-to                             | Nodejs | Python | Rust | Java | .Net | Objective C |
| ---------------------------------- |:------:|:------:|:----:|:----:|:----:|:-----------:|
| Write a DID and Query Its Verkey   | I      | I      | I    | F    | N    | N           |
| Rotate a Key                       | I      | I      | F    | F    | N    | N           |
| Save a Schema and Cred Def         | N      | I      | I    | F    | N    | N           |
| Issue a Credential                 | N      | I      | F    | F    | N    | N           |
| Negotiate a Proof                  | I      | I      | F    | N    | N    | N           |
| Send a Secure Message              | N      | I      | F    | N    | N    | N           |

Tested with versions:
nodejs v11.13.0
python 3.7.3
rustc 1.33.0

**Comment by johncallahan** [comment]
I just submitted the last PRs to complete the update of the rust how-tos   (#1565 Issue Credental and Negotiate Proof; #1572 Send Secure Message and Rotate Key).  I would next like to update the READMEs and Cargo.toml to better guide newbies.

**Comment by jovfer** [comment]
@r0qs thank you for the contribution. I hope to merge this PR soon, but please fix DCO check. You can find details about failed commit here: https://github.com/hyperledger/indy-sdk/pull/1567/checks

**Comment by r0qs** [comment]
Hi @jovfer, since the commit missing the signature wasn't the last one, I needed to rebase from it, applying the following commands below. I don't know if there is a better way to sign-off a specific commit, and I hope that I didn't mess up everything.

```
git rebase --interactive '121552d^'
git commit --all --amend --no-edit --signoff
git rebase --continue
git push --force-with-lease origin howtos-refactor
```

**Pull request merged**
