### PR TITLE
[WIP] New Inequality Predicates 

### PR DESCRIPTION
**Pull request by mikelodder7**
Once the indy-crypto crate at crates.io has been updated to 0.4.4 then Cargo.toml can be updated to point to it. Until then this won't pass the CI pipeline without Cargo pointing to the current version at https://github.com/hyperledger/indy-crypto

### CODE REVIEW

**Comment by jovfer** [comment]
@mikelodder7 colud you try to specify Dev build of Indy crypto instead of git reference?
Like `indy-crypto = "0.4.4-dev-71"`

**Comment by jovfer** [comment]
@mikelodder7 `high_cases::verifier_verify_proof::verifier_verify_proof_works_for_correct_proof` is failed on Jenkins. Could you double-check in your local env?

**Comment by mikelodder7** [comment]
Okay I updated that test case and another one that were out of date. Those passed before but once I did a new pull against hyperledger/indy-sdk I saw the problem.

**Comment by jovfer** [comment]
@mikelodder7 fix for tests seems like breaking-change in JSON API for application. In other words, new verifier/proover will be incompatible with old proover/verifier.

I've briefly review update for IndyCrypto and find https://github.com/hyperledger/indy-crypto/blame/master/libindy-crypto/src/cl/mod.rs#L847 seems like it's a root reason, isn't it?

**Comment by vimmerru** [comment]
I added WIP until we finalize versioning approach and fix backward compatibility problems.

**Comment by esplinr** [comment]
We are excited for these new inequality predicates, but the implementation would require existing proofs to be reissued. We either would need to deprecate the current signature type (CL=Camenish-Lisyanskaya), or do the work necessary to support it and a new signature type (CL2).

We eventually want to support multiple signature types. When a new one is added, the old one becomes deprecated and cannot be used for new credentials. We need to evaluate that scope of work before we can finalize these changes.

**Comment by mikelodder7** [comment]
This isn’t a signature change. It’s a proof request proof response change. Those need to be versioned.

**Comment by esplinr** [comment]
Yes they do, but the work has not yet been done.

**Comment by jovfer** [comment]
This PR is paused, please find more details in https://jira.hyperledger.org/browse/IS-1131

**Pull request closed without merging**
