### PR TITLE
Scripts to build libindy for Ubuntu using Docker

### PR DESCRIPTION
**Pull request by xaviernopre**
Signed-off-by: Xavier NOPRE <xnopre@gmail.com>

### CODE REVIEW

**Comment by xaviernopre** [comment]
> Just for clarification: what is the problem this solves? libindy should already build in ubuntu.

Hi @mattraffel . It allow to build the lib for Ubuntu target, using Docker, for example on MacOS. I'm dockerizing `indy-sdk/vcx/wrappers/python3/demo` and for this, to be able to build image for `dummy-cloud-agent`, I need to build `libindy` for Ubuntu (and I'm on MacOS)

**Comment by mattraffel** [comment]
> > Just for clarification: what is the problem this solves? libindy should already build in ubuntu.
> 
> Hi @mattraffel . It allow to build the lib for Ubuntu target, using Docker, for example on MacOS. I'm dockerizing `indy-sdk/vcx/wrappers/python3/demo` and for this, to be able to build image for `dummy-cloud-agent`, I need to build `libindy` for Ubuntu (and I'm on MacOS)

we already have a few other docker files.   Im thinking specifically this one:
https://github.com/hyperledger/indy-sdk/blob/master/libindy/ci/ubuntu.dockerfile.   

I want to make sure we are not duplicating dockerfiles.  These things can get left behind as changes are made and become broken.   Can you please look over that one, if you haven't already?

**Comment by xaviernopre** [comment]
@mattraffel As explained, my need was to build the indylib for Ubuntu without being on Ubuntu (I'a on MacOS). I have searched in all the repo, I have try manu Docker files, but none was able to help me to simply build the lib. The file `libindy/ci/ubuntu.dockerfile` is dedicated for CI (as indicated by the `ci` path), it contains unnecessary tools (java, ruby, ...), and without any commands to build the lib. My idea is to provide the simplest solution to build the lib for Ubuntu : the Docker image contains just all necessary, including the `cargo build` command, the `.sh` script help to do the job, and I have completed the existing `doc/ubuntu-build.md` file with instructions for Docker environment, especially command to extract (with `docker container cp ...`) the `.so` generated in the image.

**Comment by xaviernopre** [comment]
@mattraffel @jovfer Why not merge this PR ? I have done this work and effort. For me, this seems to be interesting and useful for other developers (for example under MacOs like me). I have answered your questions. Is there still a problem ? Thanks

**Comment by mattraffel** [comment]
@xaviernopre I'm still not convinced this is needed.  I use mac and I use the various dockerfiles in the repo.   If someone else says its needed, then I am fine with it.  I just want to avoid more dockerfiles that end up having to be maintained, or ignored.  There's other cases where this is happening.

**Comment by xaviernopre** [comment]
@mattraffel I understand and agree in general, but :
- My personnal way : arriving to the project, I did not find Docker informations ou resources to help me, all I found was explanation to build the lib on my own computer, nothing for Docker
- After many weeks immersed in the project, and some contributions (NodeJs scripts for "samples" or "how-tos"), I understand a little more the complex architecture of the project
- At that point, I found some Docker resources, but most of the resources (Dockerfile) are dedicated to CI, not really adapted to this particular need (in my opinion)
- For me, this resources are useful, dedicated to the build of lib Indy, and helpful for further new developper arriving on the project (like me some months ago)... ;-)

**Comment by vimmerru** [comment]
@xaviernopre I see multiple problems:

1. You docker images is 99% of copy paste of existing image in ci directory except additional RUN commands. It causes obvious support problems. As soon we update any new 3d party dependency version we will need to update both files.
2. Build has a lot of options. It can produce debug and release binaries, use system libsodium or custom and etc. Just one RUN command isn't enough.

It is why we have images inside ci. You can quickly get development environment by run this image and execute commands you need to produce any builds. It satisfies workflow for the most of Indy developers.

**Comment by xaviernopre** [comment]
@vimmerru I understand, and I'm not for fiels duplication. But my need is for PR #1465, I'm on MacOs and need to build the lib for Ubuntu. Searching at many places, I didn't find any information to do that, from where my work to dockerize this and share my work. You are taling about "images in the CI", but unless I'm mistaken, I have no access to this CI and to this images... On more time, I'm thinking on further developers arriving on the project, and I'm searching for helpful solution...

**Comment by jovfer** [comment]
@xaviernopre I thinkg @vimmerru mentioned files inside `libindy/ci` subfolder. Like ubuntu.dockerfile. Is this file useful for your usecase?

**Comment by xaviernopre** [comment]
@jovfer The file `libindy/ci/ubuntu.dockerfile` is very different than my file `build-libindy-ubuntu.dockerfile`. I had taken a look at the files in `ci` to avoid files duplications, but finally, I have created `build-libindy-ubuntu.dockerfile` to have the minimum requirements to build the lib, especially not installing : git, python, zip, unzip, Nodejs, NPM, OpenJDK, Ruby, ... This allows to have a dedicated Docker image with just enough to build the lib for Ubuntu. 

Another point is if someone change `libindy/ci/ubuntu.dockerfile` for CI needs, he will not know if this file is used to just build the lib (= my PR), and this build can be broken without alert.

One more time, I'm just a contributor, I'm not in the "indy" team, I have no access and no information on Ci and other of your tools, and I can testify that it's not easy to "quickly get development environment" as @vimmerru said... 

And don't forget that this PR is not just for fun, but is a needed step for PR #1465 (but I have done 2 distinct PR to be more clear and modular).

Come back to me if you have other questions or suggestions, I can change the code of my PR, but for the moment, I think this is the best way... ;-) .... I hope this can be merge soon ;-)

**Pull request closed without merging**
