### PR TITLE
new version of rustc 1.36.0

### PR DESCRIPTION
**Pull request by AxelNennker**
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

update CI/CD files to rustc 1.36.0

### CODE REVIEW

**Comment by jovfer** [comment]
@AxelNennker could you double check all entries of rust version in the codebase? as far as I remember there are few more points. I hope it's consistent everywhere so full text search `1.34.1` should be enough

**Comment by AxelNennker** [comment]
Hm, this needs https://github.com/hyperledger/indy-sdk/pull/1726 first

**Comment by jovfer** [comment]
Seems like new Rust detect more warnings:
https://build.sovrin.org/job/indy-sdk/job/indy-sdk-ci/job/PR-1727/4/execution/node/880/log/
https://build.sovrin.org/job/indy-sdk/job/indy-sdk-ci/job/PR-1727/4/execution/node/525/log/

**Comment by jovfer** [comment]
@AxelNennker FYI: I've broke this PR by one of merge to master and then fix new warning in cc6d776 commit

**Pull request merged**
