### PR TITLE
cargo update 2019 June 19

### PR DESCRIPTION
**Pull request by AxelNennker**
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

cargo update

### CODE REVIEW

**Comment by jovfer** [comment]
@AxelNennker lets see will it pass CI. And then let's try to update all Cargo.lock files across the repo to have consistency.

**Comment by AxelNennker** [comment]
I ran the tests on Ubuntu, so libindy compiles and passes tests. 
`cargo update` only replaces the version after the first non-zero number, so no breaking change if maintainers follow the rules.

**Comment by AxelNennker** [comment]
‘jenkinswindows01’ is offline 
so this is not currently building

**Comment by jovfer** [comment]
yes and Sovrin Foundation is trying to fix problem with windows agent

**Pull request merged**
