### PR TITLE
Fix Libvcx C Error Message Segfault

### PR DESCRIPTION
**Pull request by hadleym**
Fixes the current libvcx vcx_error_c_message api call.  In the current version of vcx_error_c_message, the memory returned via pointer is dropped at the end of the api call, causing undefined behavior when the wrappers dereference the returned pointer.

### CODE REVIEW

**Comment by hadleym** [comment]
@glowkey 
Please review.

**Comment by jovfer** [comment]
@hadleym please fix Java wrapper too

**Comment by jovfer** [comment]
double-check Artem's suggestion on Jenkins: yes, with incremented rust version this PR can pass build stage on Jenkins for VCX (https://github.com/jovfer/indy-sdk/commit/95b7d2a180d342473e8ad3c8e0652b04c4e7bcda).

**Comment by hadleym** [comment]
@jovfer
I will fix the Java wrapper as well as the rust version as suggested by @Artemkaaas

**Comment by hadleym** [comment]
@glowkey has found the correct reason for the python segfaults regarding `vcx_error_c_message`, and will implement a fix in his future PR.

**Pull request closed without merging**
