### PR TITLE
Update indy-walkthrough.md

### PR DESCRIPTION
**Pull request by meadoch1**
This work changes "Trust Anchor" to "Endorser" to align with the changes in 79aed586c586da8d47adb423ff3f7dcbf31fcb22

### CODE REVIEW

**Comment by meadoch1** [comment]
The SHA referenced is in indy-node.  https://github.com/hyperledger/indy-node/commit/79aed586c586da8d47adb423ff3f7dcbf31fcb22#diff-2088d14bfcb85060b0b7a97ab31573a39e6fcfba76804d1c27194fc6cea46379

**Comment by WadeBarnes** [comment]
Thanks @meadoch1.  Could you add the required DCO sign-off to your commit please.  Details here; https://github.com/hyperledger/indy-sdk/pull/2462/checks?check_run_id=4817377128

**Comment by meadoch1** [comment]
Done.  Sorry for the misstep.  I did the work via Github's editor and didn't think about a doc update triggering other checks.  Will be more mindful in the future.

**Comment by WadeBarnes** [comment]
Thanks

**Comment by WadeBarnes** [comment]
@meadoch1, I've fixed the issues causing the Jenkins builds to fail (https://github.com/hyperledger/indy-sdk/pull/2470).  If you rebase your PR on the latest from the main branch the builds should work and we can get your PR merged.  I know this is just a documentation update, but the builds passing is a gate to allow the PR to be merged.

**Pull request closed without merging**
