### PR TITLE
[DESIGN] Design of export/import

### PR DESCRIPTION
**Pull request by dkulic**
Signed-off-by: Darko Kulic <darko.kulic@evernym.com>

### CODE REVIEW

**Comment by mikelodder7** [comment]
Is there a reason we are using passwords to derive the key instead of creating the key ourselves and just using the public key for encryption and saving the private key somewhere else? Is the reason convenience to the end user?

**Comment by dkulic** [comment]
Looks like I cannot answer directly (the lack of privileges or similar), so I will write here.
1) Moderate for both (memory and cpu) is used, like in open/create of wallet.
2) The reason is to be in-line with open/create.

**Comment by mikelodder7** [comment]
Is there a reason it needs to be same as open/create?
I’m mostly okay with it but open/create leave the wallet directly under your control whereas export could be moving somewhere that isn’t. If my concern is not big enough then just leave it. Moderate setting is okay for open/create

**Comment by vimmerru** [comment]
> Is there a reason it needs to be same as open/create?

It just solves the problem in a similar way and don't have obvious drawbacks. This key is visible for user and introducing of new concept can just cause bad UX

**Comment by vimmerru** [comment]
I am ok with this design

**Pull request merged**
