### PR TITLE
Ideas for upgrading the Python-Wrapper

### PR DESCRIPTION
**Pull request by JeromeK13**
https://jira.hyperledger.org/browse/IS-1350

More Information can be read in the Jiraticket and the README.md

### CODE REVIEW

**Comment by dbluhm** [comment]
I think this architecture is fantastic. Unfortunately, especially as we find ourselves at an interesting place in the Indy/Aries lifecycle, I think we are unlikely to see this make it into the Indy SDK today; however, I think we should use this for the Aries SDK python wrapper. In the meantime, I'm not sure where would be best for this code. Perhaps just as an open PR for now.

Truly awesome work. Thanks for being willing to contribute it back to the community!

**Comment by jovfer** [comment]
@dbluhm @JeromeK13 I can see 2 options here:
1) merge to current IndySDK repo in experimental folder
2) merge to some specific folder in https://github.com/hyperledger/aries-sdk-python

I prefer the 2nd option to have aries community involved.

**Comment by JeromeK13** [comment]
Hey Guys @jovfer @dbluhm 

In my opinion, we could do both options as @jovfer recommended. Since our Python wrapper is based on Indy 1.8.- we would need to add some more thing to get it up to date with the current one. 
Anyway, I think the wrapper would have more value in the aries-sdk-python since the implementation would be easier(not to mutch code there) and would benefit from an "easy and fast" implementation of new Indy-Lib-Calls in the future.

Let me know, for which option you decided and if you need any help.

Greets
JeromeK

**Comment by jovfer** [comment]
@dbluhm are you OK with moving this PR to aries-sdk-python ? Or do you think the 1st option is better?

**Comment by JeromeK13** [comment]
@dbluhm @jovfer 
Should I create a new PR onto the Aries-SDK-Python or can you move this one?

**Comment by jovfer** [comment]
@JeromeK13 I think it's better to have the PR created by you as the author.
btw while recreation of the PR for the new repo, please fix DCO as well

**Comment by JeromeK13** [comment]
PR with fixed DCO can be found here:

https://github.com/hyperledger/aries-sdk-python/pull/5

**Comment by jovfer** [comment]
Moved to Aries repo with fixed DCO, so this PR can be closed

**Pull request closed without merging**
