### PR TITLE
Fix build error due to incorrect path

### PR DESCRIPTION
**Pull request by chaeso**
Signed-off-by: hcchae <hc.chae@sk.com>

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
@chaeso The build is failing right now, here's beginning of output related to failing command
```
+ cd libindy
+ ./android.test.sh x86
>> in runner script
/tmp/android_build/sdk /home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/libindy
/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/libindy/ci/setup.android.env.sh: line 44: adb: command not found
Error: There is no Android Virtual Device named 'x86'.
null
Creating Android SDK
Loading local repository...                                                     
[=========                              ] 25% Loading local repository...       
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=============                          ] 34% Fetch remote repository...        
[================                       ] 42% Fetch remote repository...        
[================                       ] 42% Fetch remote repository...        
[=================                      ] 44% Fetch remote repository...        
[=================                      ] 45% Fetch remote repository...        
[==================                     ] 46% Fetch remote repository...        
[==================                     ] 46% Fetch remote repository...        
[==================                     ] 47% Fetch remote repository...        
[===================                    ] 48% Fetch remote repository...        
[===================                    ] 49% Fetch remote repository...        
[===================                    ] 49% Fetch remote repository...        
[====================                   ] 50% Fetch remote repository...        
[====================                   ] 51% Fetch remote repository...        
[====================                   ] 52% Fetch remote repository...        
[====================                   ] 52% Fetch remote repository...        
[=====================                  ] 53% Fetch remote repository...        
[=====================                  ] 54% Fetch remote repository...        
[=====================                  ] 55% Fetch remote repository...        
[======================                 ] 55% Fetch remote repository...        
[======================                 ] 56% Fetch remote repository...        
[======================                 ] 57% Fetch remote repository...        
[=======================                ] 58% Fetch remote repository...        
[=======================                ] 58% Fetch remote repository...        
                                                                                
Warning: File /home/indy/.android/repositories.cfg could not be loaded.
[=======================                ] 58% Fetch remote repository...        
[=======================                ] 58% Computing updates...              
[=============================          ] 75% Computing updates...              
[=============================          ] 75% Computing updates...              
[=======================================] 100% Computing updates...             
6 of 6 SDK package licenses not accepted.
Review licenses that have not been accepted (y/N)? 
```
Here's the end of output:
```
   Compiling crossbeam-deque v0.7.2
   Compiling tinytemplate v1.0.3
   Compiling libindy v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/libindy)
   Compiling csv v1.1.3
   Compiling indy v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/wrappers/rust)
   Compiling rayon v1.3.0
   Compiling criterion v0.2.11
   Compiling indy-wallet v0.1.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/libindy/indy-wallet)
warning: function is never used: `multi_steps_create_revocation_credential`
   --> tests/interaction.rs:624:1
    |
624 | fn multi_steps_create_revocation_credential(pool: &Pool, issuer: &Issuer, prover: &mut Prover, cred_values_json: &str, cred_id: &str) -> (String, Option<String>)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

    Finished release [optimized] target(s) in 9m 34s
    Finished release [optimized] target(s) in 0.39s
/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/libindy
emulator is running
Alarms
DCIM
Download
Movies
Music
Notifications
Pictures
Podcasts
Ringtones
+ adb -e push /tmp/android_build/toolchains/linux/android-ndk-r20//sysroot/usr/lib/i686-linux-android/libc++_shared.so /data/local/tmp/libc++_shared.so
adb: error: cannot stat '/tmp/android_build/toolchains/linux/android-ndk-r20//sysroot/usr/lib/i686-linux-android/libc++_shared.so': No such file or directory
script returned exit code 1
```

**Comment by chaeso** [comment]
> @chaeso The build is failing right now, here's beginning of output related to failing command

OMG. I fixed the error you mentioned now.

**Comment by Patrik-Stas** [comment]
@chaeso seems like the same issue persists
```
   Compiling indy-sys v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/wrappers/rust/indy-sys)

   Compiling failure v0.1.6

   Compiling indy v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/wrappers/rust)

   Compiling null-payment-method v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/libnullpay)

warning: use of deprecated item 'indy::payments::build_get_payment_sources_request': please use `parse_get_payment_sources_with_from_response` instead

  --> tests/utils/payments.rs:23:5

   |

23 |     payments::build_get_payment_sources_request(wallet_handle, Some(submitter_did), payment_address).wait()

   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   |

   = note: `#[warn(deprecated)]` on by default



warning: use of deprecated item 'indy::payments::parse_get_payment_sources_response': please use `parse_get_payment_sources_with_from_response` instead

  --> tests/utils/payments.rs:28:5

   |

28 |     payments::parse_get_payment_sources_response(payment_method, resp_json).wait()

   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred

 --> tests/utils/plugin.rs:3:23

  |

3 | use std::sync::{Once, ONCE_INIT};

  |                       ^^^^^^^^^



warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred

 --> tests/utils/plugin.rs:6:55

  |

6 |         static ref CREATE_PAYMENT_METHOD_INIT: Once = ONCE_INIT;

  |                                                       ^^^^^^^^^ help: replace the use of the deprecated item: `Once::new()`



    Finished release [optimized] target(s) in 4m 28s

    Finished release [optimized] target(s) in 0.23s

/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2194/libnullpay

emulator is running

ls: /storage/emulated/0/: No such file or directory

waiting emulator FS

ls: /storage/emulated/0/: No such file or directory

waiting emulator FS

+ adb -e push /tmp/android_build/toolchains/linux/android-ndk-r20//sysroot/usr/lib/i686-linux-android/libc++_shared.so /data/local/tmp/libc++_shared.so

adb: error: cannot stat '/tmp/android_build/toolchains/linux/android-ndk-r20//sysroot/usr/lib/i686-linux-android/libc++_shared.so': No such file or directory

script returned exit code 1
```

Note that I am just providing this information as there's currently no public access to Jenkins, but someone will still need to review this (I don't have experience with android builds).

**Comment by chaeso** [comment]
> @chaeso seems like the same issue persists

I think you did not patch the latest changes (revision = 246d2ba)


- "${TOOLCHAIN_DIR}/sysroot/usr/lib/${TRIPLET}/libc++_shared.so" "/data/local/tmp/libc++_shared.so"
+"${TOOLCHAIN_DIR}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/${TRIPLET}/libc++_shared.so" "/data/local/tmp/libc++_shared.so"

**Comment by Patrik-Stas** [comment]
@chaeso you are right, that's strange. It's automated build, but seems like it indeed didn't use your latest changes. 

I can't rerun pipeline manually, can you push any change to trigger rerun?

**Comment by chaeso** [comment]
> I can't rerun pipeline manually, can you push any change to trigger rerun?

Thanks. I did PR again

**Pull request closed without merging**
