### PR TITLE
Node.js wrapper

### PR DESCRIPTION
**Pull request by farskipper**
The wrapper is almost finished. It supports the full libindy api with the exception of `indy_register_wallet_type`. It’s been published to npm and the installation process works. The usage, and api is fully documented along with notes on contributing. (see it [here](https://github.com/Picolab/indy-sdk/blob/master/wrappers/nodejs/README.md)) It's been shown to work on linux and osx.

I updated the jenkins ci/cd files. To publish the package we will need an npm user account. Also the build servers will need the LTS version of nodejs. [The n bash script](https://github.com/tj/n) is the easiest way to install node and switch between versions.

What’s left:
- [x] Finish testing the api (about 30% done)
- [ ] Windows testing (I don’t anticipate too much trouble since it's using [nan](https://github.com/nodejs/nan))

### CODE REVIEW

**Comment by ArthurManz** [comment]
This is simply AWESOME!! :+1:

**Comment by vimmerru** [comment]
@farskipper 

Thanks for contribution. We will look to it soon. One thing that you can solve now is fixing of commits to satisfy our DCO check. See https://github.com/probot/dco#how-it-works for details.

You can use interactive rebase like this:

git rebase --exec 'git commit --amend --no-edit -n --signoff' -i branch_name_or_hash

**Comment by farskipper** [comment]
Thanks @vimmerru I got those commits signed off now.

**Comment by vimmerru** [comment]
@farskipper Do you have progress with tests? 

There was big PR merged related to credentials revocation feature https://github.com/hyperledger/indy-sdk/pull/550. It will require update in your wrapper.

**Comment by farskipper** [comment]
@vimmerru Just finished updating to support the #550 changes. I'll make time next week to work more on the tests.

**Comment by farskipper** [comment]
@vimmerru I finished the tests. I haven't been able to view ci.evernym.com to see if my Jenkins file changes are working for this wrapper. Other than that, I'm ready to merge.

Here's the link to easily view the readme: https://github.com/Picolab/indy-sdk/tree/master/wrappers/nodejs

**Comment by vimmerru** [comment]
@farskipper Thanks, I will check it deeply soon

**Comment by vimmerru** [comment]
@farskipper 

One question. We are trying to keep wrappers code and especially tests consistent for all wrappers. As i can see you use different tests organization for this wrapper. It can cause supportability problems later.  Do you plan to maintain this wrapper?

**Comment by farskipper** [comment]
The test files are partitioned like the directories in the python wrapper. But yes, with the intent of being long files instead of directories (it's an ethos shared by other nodejs projects). Admittedly I have fewer tests than the python wrapper. My goal was to simply assert the function binding exists and does the json dance. For example, many of the build-a-request functions I don't submit the transaction b/c I'm just testing that the binding exists and returns a json object for the request. The cpp and js code for this wrapper is very thin and repetitive.

The test runner, [ava](https://www.npmjs.com/package/ava), runs each test concurrently. Every test creates its own pool/wallet(s) so tests are atomic. Yes, right now every file has a single test that calls several indy functions and is stateful :astonished: but it’s really not that bad IMHO when the api changes you either change a bunch of small tests or you change one long test. Either way there is work and debugging involved.

Yes, I plan on maintaining it. ...assuming I don’t get hit by a bus :)
And as time goes on, we can always add more tests.

**Comment by vimmerru** [comment]
There are some tests called "demo". They illustrate the main workflows and can be used as code example. Can you implement these tests https://github.com/hyperledger/indy-sdk/tree/master/wrappers/python/tests/demo ?

**Comment by farskipper** [comment]
Sure, I can add those

**Comment by vimmerru** [comment]
Also i suggest to merge this in 2 steps:

1. Merge the code without integration to CI/CD pipeline
2. Integrate to CI/CD as a next step in dedicated PR

It will allow to merge 1 much faster

**Comment by farskipper** [comment]
Good idea, I'll take those out later today.

**Comment by farskipper** [comment]
Ok, ci config is in #714 and cd in #715

**Comment by vimmerru** [comment]
I approved the PR, but merge can be a bit postponed until 1.4 version is released.

**Comment by vimmerru** [comment]
@jovfer Can we start merging this?

**Pull request merged**
