### PR TITLE
support setting ZMQ socks proxy

### PR DESCRIPTION
**Pull request by vitalrev**
implementation for issue [#2399](https://github.com/hyperledger/indy-sdk/issues/2399)

Signed-off-by: Vitalij Reicherdt <vitalij.reicherdt@commerzbank.com>

### CODE REVIEW

**Review by dhh1128 — APPROVED** [review]
Nice solution to a pesky problem! Thank you!

**Comment by vitalrev** [comment]
Thanks!
As first-time contributor, i can not merge this pull request by my self.
Waiting for approval and merge from a maintainer with write access...

**Comment by dhh1128** [comment]
Although I have rights to merge, I am not as close to this code as I used to be. I suggest that we get @jovfer to review.

Sergey, this PR looks very straightforward; <1 min for you to review. If you give your approval, I will merge it?

**Comment by jovfer** [comment]
@vitalrev Please take a look on API params related to pool open operation https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/api/pool.rs#L68-L82
Should this ZMQ setting be a part of API params or do you suggest to ignore api capability and use env variable for the setting?

@dhh1128 thanks for the heads up.

**Comment by vitalrev** [comment]
@jovfer thank you for support!
what you mean is the pool configuration [here](https://github.com/hyperledger/indy-sdk/blob/efb72154dab94498861c43f9ac5208174e9b702c/libindy/src/services/pool/mod.rs#L146) and Socket creation [here](https://github.com/hyperledger/indy-sdk/blob/efb72154dab94498861c43f9ac5208174e9b702c/libindy/src/services/pool/mod.rs#L328)
This is an [inproc://{}](http://api.zeromq.org/2-1:zmq-inproc) socket for ØMQ local in-process (inter-thread) communication transport. 

But we need the socks proxy configuration only for the communication to the remote nodes via `tcp://`... and this is implemented in networker.rs `RemoteNode.connect`.

**Comment by jovfer** [comment]
@vitalrev sorry, didn't get your point.

The pool config from API goes down to the service as you [linked](https://github.com/hyperledger/indy-sdk/blob/efb72154dab94498861c43f9ac5208174e9b702c/libindy/src/services/pool/mod.rs#L146) 
but then it's forwarded not to internal sockets, but to `Pool::new(...)` [here](https://github.com/hyperledger/indy-sdk/blob/efb72154dab94498861c43f9ac5208174e9b702c/libindy/src/services/pool/mod.rs#L157). Finally is split to separate values and some of them is available in `RemotNode.connect`.

**Comment by vitalrev** [comment]
@jovfer  ok, I'm trying to include the `socks_proxy` config in the `PoolOpenConfig` and pass it on to RemoteNode.

**Comment by vitalrev** [comment]
@jovfer I rebuilt it ... it became a little more than 2 lines of code. I hope it goes with your suggestion. 
Please review

**Review by jovfer — APPROVED** [review]

**Comment by dhh1128** [comment]
I am going to merge this, now that @jovfer has approved.

**Comment by vitalrev** [comment]
> I am going to merge this, now that @jovfer has approved.

thank you... but 2 build steps are still in progress

**Pull request merged**
