### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by trthhrtz**
Hi!
Did some grammar corrections + code example pep8 style improvements. 
It is strange when Faber College is addressed as 'he did something' when it should be addressed as 'it did something'. Besides, I think this he/it substitution will make it easier for the reader to differentiate between Steward and Faber.

Also on the line 232, I did not get who is addressed as 'her'

Signed-off-by: Kuzma Leshakov k.leshakov@yandex.ru

### CODE REVIEW

**Comment by trthhrtz** [comment]
Signed-off-by: kuzma.leshakov k.leshakov@yandex.ru

**Comment by jovfer** [comment]
@trthhrtz please fix DCO in the first commit of PR.

**Comment by trthhrtz** [comment]
@jovfer , resolved conflicts. Could you please re-review?

**Comment by trthhrtz** [comment]
@vimmerru , could you please take a look?

**Pull request merged**
