### PR TITLE
added dkms documents

### PR DESCRIPTION
**Pull request by brentzundel**
Added dkms requirements docs in .pdf format.

### CODE REVIEW

**Comment by brentzundel** [comment]
This pull request adds pdf documents to the repo that were formerly stored in google docs and linked to in the main dkms document. Adding them will enable us to update the links in the main dkms document so they no longer point to google drive.

**Comment by vimmerru** [comment]
@brentzundel Are you sure that we can store here documents with "Evernym" name? What is the license?

**Comment by brentzundel** [comment]
the PR approval and merging process is at best obscure and difficult to follow, at worst deliberately obtuse and byzantine. Documentation of the way the process is supposed to work would be extremely beneficial.

**Comment by brentzundel** [comment]
This PR has been superseded by https://github.com/hyperledger/indy-sdk/pull/649

**Pull request closed without merging**
