### PR TITLE
Fix taa py wrapper

### PR DESCRIPTION
**Pull request by krgko**
I tried to use vcx with the sovrin builder network and got an error while starting `faber.py` at step 3. Before fixes, it always returns.
```bash
#1 Provision an agent and wallet, get back configuration details
#2 Initialize libvcx with new configuration
#2.1 Accept transaction author agreement
#3 Create a new schema on the ledger
Traceback (most recent call last):
  File "faber.py", line 194, in <module>
    loop.run_until_complete(main())
  File "/home/user/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "faber.py", line 73, in main
    schema = await Schema.create(f'schema{str(random.randint(1, 101))}', 'degree schema asd', version, ['email', 'first_name', 'last_name'], 0)
  File "/home/user/Desktop/blockchain/indy-sdk/vcx/wrappers/python3/vcx/api/schema.py", line 106, in create
    schema = await Schema._create("vcx_schema_create", constructor_params, c_params)
  File "/home/user/Desktop/blockchain/indy-sdk/vcx/wrappers/python3/vcx/api/vcx_base.py", line 47, in _create
    cls.create.cb)
vcx.error.VcxError: (<ErrorCode.DuplicateSchema: 1088>, {'backtrace': '', 'cause': 'Reject { reason: "client request invalid: InvalidClientTaaAcceptanceError(\\\'Incorrect Txn Author Agreement(digest=273df4edd0756bc4354f587e2f73db01acee711f925fef69bc85f878c3b7dc15) in the request\\\',)" }', 'error': 'Duplicate Schema: Ledger Already Contains Schema For Given DID, Version, and Name Combination', 'message': 'Error: Duplicate Schema: Ledger Already Contains Schema For Given DID, Version, and Name Combination\n  Caused by: Reject { reason: "client request invalid: InvalidClientTaaAcceptanceError(\\\'Incorrect Txn Author Agreement(digest=273df4edd0756bc4354f587e2f73db01acee711f925fef69bc85f878c3b7dc15) in the request\\\',)" }\n'})
```

As tested on python cli
```bash
>>> test_str = "hashed_data"
>>> test_str
'hashed_data'
>>> import json
>>> json.dumps(test_str)
'"hashed_data"'
```

The string from json.dumps() result on `vcx_set_active_txn_author_agreement_meta` will have extra single quote that might have transaction author agreement always incorrect.

After removed json.dumps() from `vcx_set_active_txn_author_agreement_meta` all steps work

Sorry for close previous PR but, due to accidentally commit has been pushed that why I close it. It would be great if any contributor can remove the previous PR.

For the comments earlier are

-----
@mirgee 23 hours ago Contributor
What is the reason that json.dumps() was used previously? The typing clearly specifies str... Anyway, maybe we should raise a TypeError if text, version and hash are not either None or str.

-----
@Patrik-Stas 21 hours ago Contributor
Thanks for contribution @krgko ! +1

I don't know if it just me, but it seems like Sovrin BuilderNet is having some issues so it's difficult to verify the changes. I tried to basically port these changes to nodejs demo and run against Sovrin BuilderNet but getting probably unrelated issue:

```bash
TRACE|indy::services::payments      |           src/services/payments.rs:450 | _handle_constraint <<< result: Err(IndyError { inner:

The requester role "101" doesn't meet to constraint ""2"".

The transaction is not allowed to a requester })
```

@mirgee any luck testing this?

### CODE REVIEW

**Comment by krgko** [comment]
@mirgee I think we should not be check at the method of wrapper level and leave them to the user's application to check the params. But, we might need to check to allow the case for` text + version` and `only digest` instead?

Or you think we need to check all of them?

**Comment by mirgee** [comment]
I don't understand why it was necessary to create a new PR... Anyway. as for @Patrik-Stas 's question, as I said in the now disappeared comment, I veryfied that TAA works against Sovrin BuildNet. However, it doesn't run agaist node pool running on localhost (i.e. the vcx config used in the demo).

Also, it seems that we agree with @Patrik-Stas that the demo shouldn't use external ledger.

**Comment by krgko** [comment]
@mirgee You're right the external ledger should not be included in the demo. So, this PR will be closed?

Sorry to create a new PR and close the old one.

**Comment by krgko** [comment]
@Patrik-Stas I have tried to implement the same logic to NodeJS wrapper's demo and it works fine. without any modification of NodeJS wrapper.

**Comment by Patrik-Stas** [comment]
> @mirgee You're right the external ledger should not be included in the demo. So, this PR will be closed?
> 
> Sorry to create a new PR and close the old one.

Don't get us wrong, it's a good PR 🙂👍 The demo should run against local ledger, but the added capability to run it against TAA enabled ledger is nice.

>  I have tried to implement the same logic to NodeJS wrapper's demo and it works fine. without any modification of NodeJS wrapper.

Oh cool! If you still have that code, it will be great if you add that to this PR as well.

**Comment by krgko** [comment]
@Patrik-Stas For running the demo with sovrin builder-net a DID and VerKey should pass NYM registration to assign the role to transaction endorser to create schemas and credential definitions.

Hope this helps.

**Comment by Patrik-Stas** [comment]
@krgko Thanks for adding the JS stuff! It worked for me out of the box. 

I am having issue with python version though. This is what I did:
- Created some seed X
- Generated DID and Verkey from it
- Assigned it endorser role via the self service
- changed `enterprise_seed` in config to my seed X
When it the faber in the demo tries to create schema, it throws this:
```
Traceback (most recent call last):
  File "faber.py", line 190, in <module>
    loop.run_until_complete(main())
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "faber.py", line 71, in main
    schema = await Schema.create('schema_uuid', 'degree schema', version, ['email', 'first_name', 'last_name'], 0)
  File "/Users/ABPS823/.virtualenvs/vcxdemo/lib/python3.7/site-packages/vcx/api/schema.py", line 107, in create
    schema = await Schema._create("vcx_schema_create", constructor_params, c_params)
  File "/Users/ABPS823/.virtualenvs/vcxdemo/lib/python3.7/site-packages/vcx/api/vcx_base.py", line 47, in _create
    cls.create.cb)
vcx.error.VcxError: (<ErrorCode.DuplicateSchema: 1088>, {'backtrace': '', 'cause': 'Reject { reason: "client request invalid: InvalidClientTaaAcceptanceError(\\\'Incorrect Txn Author Agreement(digest=273df4edd0756bc4354f587e2f73db01acee711f925fef69bc85f878c3b7dc15) in the request\\\',)" }', 'error': 'Duplicate Schema: Ledger Already Contains Schema For Given DID, Version, and Name Combination', 'message': 'Error: Duplicate Schema: Ledger Already Contains Schema For Given DID, Version, and Name Combination\n  Caused by: Reject { reason: "client request invalid: InvalidClientTaaAcceptanceError(\\\'Incorrect Txn Author Agreement(digest=273df4edd0756bc4354f587e2f73db01acee711f925fef69bc85f878c3b7dc15) in the request\\\',)" }\n'})
```
The stuff about duplicate schema can be ignored, I've noticed this is bug in LibVCX - when there's issue with TAA, it throws this incorrect error. Probably this part is more of our interest
`Incorrect Txn Author Agreement(digest=273df4edd0756bc4354f587e2f73db01acee711f925fef69bc85f878c3b7dc15) in the request`

I haven't used python vcx wrapper much myself, do you know by chance how to enable more detailed logging on it?

**Comment by mirgee** [comment]
@krgko As @Patrik-Stas said, of course we appreciate your contribution, thank you for the addition to node demo as well:+1: 

@Patrik-Stas I think you can enable more detailed logging in demo by adding
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
to `faber.py / `alice.py`? I tested only using by using local and sovrin builder net genesis file, and with the second one TAA in python demo worked...

**Comment by Patrik-Stas** [comment]
Yup I got it working now. I found it was issue on my side accidentally using incorrect version of the python wrapper wheels. So I got both demos working.

There 2 things to fix to get this merged:
1. Check instructions regarding DCO https://github.com/hyperledger/indy-sdk#how-to-contribute Every commit needs to be signed (probably the easier way for you now is to squash these commits and sign the squashed one)

2. We need to get pipeline passing. I don't have access to Jenkins pipeline yet. @jovfer could yo please grant me access to Jenkins pipeline?

**Comment by krgko** [comment]
Thank you for your help @Patrik-Stas, @mirgee. :thumbsup::thumbsup::smile:

**Comment by jovfer** [comment]
We are pausing the pipeline for now, please ignore next status from Jenkins. I will re-run it later and update this comment.

**Pull request merged**
