### PR TITLE
typedef Result for IndyError

### PR DESCRIPTION
**Pull request by AxelNennker**
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

As said here it is common practise to wrap errors and to improve readability by using a type definition for our errors e.g.: type Result<T> = result::Result<T, IndyError>;
https://doc.rust-lang.org/rust-by-example/error/multiple_error_types/wrap_error.html

The libindy code has the mentioned 'boilerplate' code already.

I think we can use '?' more often too
https://doc.rust-lang.org/rust-by-example/error/multiple_error_types/reenter_question_mark.html

### CODE REVIEW

**Comment by AxelNennker** [comment]
Are the places this PR changed OK and it can be merged?

Axel

Related to this I am wondering Why does
SubmitAck(
i32, // cmd_id
Result<String, PoolError>, // result json or error
),
return a PoolError and not an IndyError?
in file https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/commands/ledger.rs#L45

**Comment by vimmerru** [comment]
> Related to this I am wondering Why does
> return a PoolError and not an IndyError?

Because it is Ack from Pool service, not request from the user

**Comment by vimmerru** [comment]
> Are the places this PR changed OK and it can be merged?

It is ok, we will merge it, but most probably in a few days as we have a lot of important PRs in merge queue

**Comment by vimmerru** [comment]
@AxelNennker Could you solve conflict and remove WIP tag after it?

**Comment by vimmerru** [comment]
@AxelNennker Could you solve conflict and remove WIP tag after it?

**Comment by AxelNennker** [comment]
I resolved the merge conflict. It stemmed from the introduction of two new methods import and export.

**Pull request merged**
