### PR TITLE
Enable Ios wrapper to support xcode version 10.1

### PR DESCRIPTION
**Pull request by WandyLau**

### CODE REVIEW

**Comment by jovfer** [comment]
@Artemkaaas please run this PR only for iOS on Jenkins and share results of our CI with @WandyLau

**Comment by WandyLau** [comment]
What do you think it is error? Or any more info about this? 

I ran it again I got the almost the same output. But it is not error. I can build the indy and run all the test cases. And you can delete these two lines in indy-demo project file:
>4E103A157091ECB5654FA9BE /* Pods-Indy-demo-Indy-demoTests.debug.xcconfig */,
  33861E44A9CE72607F003ED4 /* Pods-Indy-demo-Indy-demoTests.release.xcconfig */,

**Comment by WandyLau** [comment]
@Artemkaaas 
this error means that the head files are missing. Usually The path is not right. I used the out_pod as the head file root directory, and for "<libindy/*.h>, there should one directory named libindy in the out_pod, including all the corresponding head files. Yes I think the CI file should be modified.

**Comment by NanoBytesInc** [comment]
Any progress on this?

**Comment by WandyLau** [comment]
@NanoBytesInc I thought they have updated the repo already against xcode 10.0

**Comment by jovfer** [comment]
I've asked @Artemkaaas and @mattraffel check current master in his environments and sounds like now master branch is compatible with XCode 10.1.

@WandyLau does master branch version work for you?
If so, should we close this PR and mark https://jira.hyperledger.org/browse/IS-1096 as done?

**Comment by WandyLau** [comment]
@jovfer Thanks for the support. Last time as I discussed with @Artemkaaas , the xcode 10.0 is supported. But if it is done now I am ok with this issue closed.

**Comment by jovfer** [comment]
It seems like current master is support 10.1 XCode.
Fill free to re-open PR and re-raise issue if some new problem will be detected

**Pull request closed without merging**
