### PR TITLE
docs: Update getting started dockerfile

### PR DESCRIPTION
**Pull request by rach-id**
Ubuntu 16.04 still installs `Python:2.7` and `pip`. Thus, the `getting-started` docker image doesn't build as expected.
So, an update to `Ubuntu:20.04` is needed for the images to build successfully.

### CODE REVIEW

**Comment by dlz21** [comment]
This fixes build error, how can we get someone to look at this?

**Comment by SweeXordious** [comment]
If someone is interested in merging this, I can fix the pipelines :D

**Comment by WadeBarnes** [comment]
@SweeXordious, You need to add DCO sign-off to your commits.  Details here; https://github.com/hyperledger/indy-sdk/pull/2438/checks?check_run_id=4056269767

**Comment by SweeXordious** [comment]
@WadeBarnes Can you please let me know why the CI is not passing ? I don't have access to jenkins

**Comment by WadeBarnes** [comment]
> @WadeBarnes Can you please let me know why the CI is not passing ? I don't have access to jenkins

It's a rust (cargo) version issue that is failing the builds. https://github.com/hyperledger/indy-sdk/pull/2452#issuecomment-988177968

**Comment by SweeXordious** [comment]
Thanks, will wait until it's fixed then rebase

**Comment by WadeBarnes** [comment]
A fix for the build issues has been implemented (https://github.com/hyperledger/indy-sdk/pull/2470).  Please rebase this PR on the latest from the main branch so it is no longer blocked by the related build issues.

**Comment by WadeBarnes** [comment]
@SweeXordious, Sorry, it looks like the merge form another PR has created a conflict with your change.  Could you please review.

**Comment by SweeXordious** [comment]
@WadeBarnes Thanks for letting me know. Conflicts resolved.

**Pull request closed without merging**
