### PR TITLE
Android wrapper for libindy

### PR DESCRIPTION
**Pull request by faisal00813**
Signed-off-by: Mohammad Abdul Sami <faisl00813@gmail.com>

### CODE REVIEW

**Comment by jovfer** [comment]
Hello @faisal00813, I'm glad to see your contribution to Indy again!
regarding this particular PR, could you remove binaries (and from git history as well, e.g. squash commits)

**Comment by AxelNennker** [comment]
Hi @faisal00813, good to hear from you again!

Regarding this PR. It does not work for me on Ubuntu 16.04 because the permissions seem to be wrong. I think that build.sh and gradlew should be executable. Also, error checking in the shell scripts would be nice.

What I did:
1 git clone https://github.com/faisal00813/indy-sdk
2 cd indy-sdk
3 git checkout libindy-android-wrapper
4 cd ../../libindy 
5 ./build-libindy-android.sh
6 cd ../wrappers/android
7 chmod +x build.sh
8 chmod +x gradlew
9 bash build.sh

```
ignisvulpis@namenlos:~/development/faisal00813/indy-sdk/wrappers/android$ bash build.sh 
~/development/faisal00813/indy-sdk/libindy ~/development/faisal00813/indy-sdk/wrappers/android
~/development/faisal00813/indy-sdk/wrappers/android

> Task :transformNativeLibsWithStripDebugSymbolForDebug 
Unable to strip library '/home/ignisvulpis/development/faisal00813/indy-sdk/wrappers/android/build/intermediates/transforms/mergeJniLibs/debug/0/lib/arm64/libgnustl_shared.so' due to unknown ABI. Packaging it as is.
Unable to strip library '/home/ignisvulpis/development/faisal00813/indy-sdk/wrappers/android/build/intermediates/transforms/mergeJniLibs/debug/0/lib/arm64/libindy.so' due to unknown ABI. Packaging it as is.

> Task :transformNativeLibsWithStripDebugSymbolForRelease 
Unable to strip library '/home/ignisvulpis/development/faisal00813/indy-sdk/wrappers/android/build/intermediates/transforms/mergeJniLibs/release/0/lib/arm64/libgnustl_shared.so' due to unknown ABI. Packaging it as is.
Unable to strip library '/home/ignisvulpis/development/faisal00813/indy-sdk/wrappers/android/build/intermediates/transforms/mergeJniLibs/release/0/lib/arm64/libindy.so' due to unknown ABI. Packaging it as is.


BUILD SUCCESSFUL in 12s
51 actionable tasks: 48 executed, 3 up-to-date
ignisvulpis@namenlos:~/development/faisal00813/indy-sdk/wrappers/android$ 
```

Maybe put libgnustl_shared.so next to the downloaded build artifacts https://repo.sovrin.org/android/libindy/deps/ ?

**Comment by faisal00813** [comment]
@jovfer @AxelNennker Its a pleasure to contribute to this project. :)

@jovfer I will remove `libindy-debug.aar` which I accidentally committed. But I would need a place to host libgnustl_shared.so for each architecture, till then I assumed repo would be a good place to host them as they are relatively small binaries.
As @AxelNennker we can put it in repo.sovrin.org.

@AxelNennker I agree the build script is rudimentary at the moment as I have some other stuff on my plate. I intend to make the script and sample project more robust and descriptive in future.

**Comment by faisal00813** [comment]
@jovfer  I have removed the binaries from the history and added few fixes. Please let me know if there are more changes.

The build script downloads the gnustl binaries from my fork of this repo https://github.com/sovrin-foundation/indy-android-dependencies. Will update the download url in build.sh when this PR is merged https://github.com/sovrin-foundation/indy-android-dependencies/pull/2
But it should not be a blocker for this PR.

Thanks.

**Comment by faisal00813** [comment]
@jovfer This is PR seems to be ready for merge. Can you please have a look?

**Comment by jovfer** [comment]
@faisal00813 thanks for reminder, I'll take a look asap.

While #1887 we removed gnustl dependency of libindy from android artifacts, could you check the impact on your PR?

**Comment by faisal00813** [comment]
That definitely has an impact on this PR. I will have to change the gnustl with libc++. Let me try it with the updated master branch.
Thanks for the update.

**Comment by jovfer** [comment]
@faisal00813 could you fix DCO check for the latest commit?

**Pull request closed without merging**
