### PR TITLE
Remove package-lock.json file from vcx nodejs wrapper

### PR DESCRIPTION
**Pull request by Artemkaaas**
Signed-off-by: artem.ivanov <artem.ivanov@dsr-company.com>

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
@jovfer Probably not critical to include package-lock.json in vcx demo, but a rule of thumb is to include package-lock.json in repository. The reasoning behind it is here https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5/44210813 Particularly good to note comments by curiousdannii  and  Panu Horsmalahti under the accepted answer.

**Comment by mattraffel** [comment]
Why are we duplicating what I already did and proved it didn't work?

**Comment by Artemkaaas** [comment]
@Patrik-Stas In my opinnion vcx demo should be moved to the samples folder. And lock file will be committed there. But for wrapper lock file shouldn't be commited. I also have checked if openssl and zmq wrappers do i.

**Comment by Artemkaaas** [comment]
@mattraffel Yesterday you wrote that couldn't achive changes we had agreed before (removing lock files from folder).
I had tried the solutionyou you had provided and it didn't work for me.
I tried to solve tsconfig errors and pretty fast found the solution.

**Comment by jovfer** [comment]
@mattraffel in other words Artem not duplicates but extend your attempt and have found a solution

@Patrik-Stas @Artemkaaas @mattraffel I think we have 2 options: 
1) merge this one (removing lock files)
2) or use `npm audit fix` and just increment problematic dependency issue.

2nd option wasn't work in Matt's environment (the PR #1528 just re-generates lock files, without increment of nested dependency version)
but in my env I'm able to have updated dependency and resolved security warning

**Comment by jovfer** [comment]
alternative solution #1528 has been merged

**Pull request closed without merging**
