### PR TITLE
Create acceptance.md

### PR DESCRIPTION
**Pull request by VladimirWork**
Here are manual acceptance steps for Indy SDK.

### CODE REVIEW

**Review by ianco — APPROVED** [review]

**Comment by ianco** [comment]
Can you please DCO sign your commit?  See https://github.com/hyperledger/indy-sdk/pull/2281/checks?check_run_id=1378952060
Thanks

**Review by ianco — APPROVED** [review]

**Comment by ianco** [comment]
(ci) please test

**Comment by ianco** [comment]
ci test this please

**Comment by ianco** [comment]
CI test this please

**Comment by ianco** [comment]
@VladimirWork can you please update this PR to the latest code in the main branch?  I'd like to merge the PR and I don't have access to update the branch myself.  Thanks!

**Comment by VladimirWork** [comment]
Somehow I also cannot update this branch so I created another PR from my fork and it is in sync with current master: https://github.com/hyperledger/indy-sdk/pull/2285

**Comment by ianco** [comment]
Thanks @VladimirWork  I'll merge the new PR

**Pull request closed without merging**
