### PR TITLE
update rust version to 1.34.1

### PR DESCRIPTION
**Pull request by AxelNennker**
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

I read that there were performance improvements in rust and that build time are shorter.
Let's see

### CODE REVIEW

**Comment by jovfer** [comment]
@AxelNennker seems like the build is failed due to warnings
https://build.sovrin.org/job/indy-sdk/job/indy-sdk-ci/job/PR-1615/3/execution/node/221/log/

as far as I remember, you have already fixed the same warning in libindy, but not in libnullpay? Could you update libnullpay (and may be libvcx, not sure) in this PR please?

**Comment by AxelNennker** [comment]
I searched through all file using `find . -type f -exec fgrep 1.32.0 {} \; -print` 
Seem to have searched differently before and found two more today but not libnullpay

**Comment by jovfer** [comment]
@AxelNennker should https://github.com/hyperledger/indy-sdk/pull/1592 changes be applied to libnullpay too?

**Comment by AxelNennker** [comment]
> @AxelNennker should #1592 changes be applied to libnullpay too?

Doesn't hurt. I thought that pulling master, merging and pushing did that already.

**Comment by AxelNennker** [comment]
PR for nullpay is sent

**Comment by jovfer** [comment]
Seems like vcx also has deprecated atomic declaration
https://build.sovrin.org/job/indy-sdk/job/indy-sdk-ci/job/PR-1615/7/execution/node/1033/log/

**Comment by AxelNennker** [comment]
I've put the changes into its own PR.

**Pull request merged**
