### PR TITLE
 Add sample script to illustrate revocation process

### PR DESCRIPTION
**Pull request by xaviernopre**
I have added a NodeJs script `anoncredsRevocationScenario.js` to illustrate the revocation process, revoking a credential, and then verifying the proof at different timestamps

### CODE REVIEW

**Comment by jovfer** [comment]
@xaviernopre please fix DCO in 40ac80c commit

**Comment by jovfer** [comment]
@Artemkaaas please review

**Comment by xaviernopre** [comment]
Hi @jovfer , I saw the alert on the PR, we are fixing it....

**Comment by jovfer** [comment]
@xaviernopre thanks
just FYI: now there is a tab `Checks` in GH UI. It contains the useful information like what commit is fail DCO check and why.

**Comment by xaviernopre** [comment]
@jovfer Hi. I think all is OK now. Can you confirm ?

**Comment by xaviernopre** [comment]
I cannot resolve DCO problem, I close this PR to open a new one

**Pull request closed without merging**
