### PR TITLE
postgres_storage: Changed type in unsafe block to be able to compile on arm64 architecture 

### PR DESCRIPTION
**Pull request by nebucaz**
@WadeBarnes thanks for the hint:  Replaced `*const i8` with `libc::c_char` in `unsafe {}` blocks in file `lib.rs` to be able to compile on linux/arm64 architecture. Now compiles on Ubuntu 20.04 aarch64 and MacOS 12.0.1 (Apple M1, arm64/v8). Rust Version: 1.56.0

`unsafe { *tags_json_ptr = record.tags.as_ptr() as *const libc::c_char; }`

*Deprecation Warnings*
Changed [deprecated use](https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#errordescription-is-deprecated) of `err.description()` to silence warnings
`warning: use of deprecated item std::error::Error::description: use the Display impl or to_string()`
 in `src/common.rs, src/wallet.rs, src/crypto.rs`

### CODE REVIEW

**Comment by ianco** [comment]
Hi @ nebucaz, FYI all commits to Hyperledger repositories need to be DCO signed off, can you update your commit?  See https://github.com/hyperledger/indy-sdk/pull/2453/checks?check_run_id=4406963855
Thanks for the contribution!

**Review by ianco — APPROVED** [review]
Looks good to me

**Comment by WadeBarnes** [comment]
A fix for the build issues has been implemented (https://github.com/hyperledger/indy-sdk/pull/2470).  Please rebase this PR on the latest from the main branch so it is no longer blocked by the related build issues.

**Comment by WadeBarnes** [comment]
@nebucaz, When you have a moment:
 
> A fix for the build issues has been implemented (#2470). Please rebase this PR on the latest from the main branch so it is no longer blocked by the related build issues.

**Pull request closed without merging**
