### PR TITLE
indy-pool.dockerfile -> ubuntu.dockerfile

### PR DESCRIPTION
**Pull request by AxelNennker**

### CODE REVIEW

**Comment by sklump** [comment]
How does this improve the software? The docker file builds an indy pool on ubuntu. Isn't the more important abstraction the indy pool, not the OS image on which it operates? Maybe something like indy-pool.ubuntu.dockerfile might serve if it absolutely has to change?

**Comment by vimmerru** [comment]
It is just indy-pool. Base image doesn't matter here

**Comment by AxelNennker** [comment]
Important thing is that the README.md fits the existing files.
```
ignisvulpis@namenlos:/tmp/indy-sdk/libindy$ ls ci
amazon.dockerfile  indy-sdk.spec.in  libindy-rpm-build-and-upload.sh  setup.android.env.sh  ubuntu.dockerfile
ignisvulpis@namenlos:/tmp/indy-sdk/libindy$ 
```
The PR fixes the README.md 
Maybe somebody had a reason to rename indy-pool.dockerfile to ubuntu.dockerfile.
I would be OK with renaming it back and scrap this PR but the README.md should have working command line instructions

**Comment by jovfer** [comment]
```
DSRs-MacBook-Pro:indy-sdk sminaev$ pwd
/Users/sminaev/projects/indy-sdk
DSRs-MacBook-Pro:indy-sdk sminaev$ ls ci/*.dockerfile
ci/indy-pool.dockerfile
```
`libindy/ci` is a different folder
`ci` is referenced from README.md isn't it?

**Comment by AxelNennker** [comment]
@jovfer is right, I confused the docker file used to build the Android libraries with the docker file used to run the pool. My bad.
Closing this. Sorry.

**Comment by jovfer** [comment]
@AxelNennker np, thanks for tracking the state of documentation. btw due to your note I've looked through our CI directories and find out some inconsistency like we have libindy/ci/<platform>.dockerfile but same file is also used for other parts.
So we have helpful output from this conversation, no need to apologize!

**Pull request closed without merging**
