### PR TITLE
Fix build error due to incorrect path.

### PR DESCRIPTION
**Pull request by chaeso**
Signed-off-by: chaeso <chaeso@gmail.com>

### CODE REVIEW

**Comment by chaeso** [comment]
@Patrik-Stas / Could you please let me know the error log?

**Comment by Patrik-Stas** [comment]
@chaeso Here you go
```
+ cd libnullpay

+ ./android.test.sh x86

Found local INDY_DIR=/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/libindy/target/i686-linux-android/release/

>> in runner script

/tmp/android_build/sdk /home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/libnullpay

Deleting file /home/indy/.android/avd/x86.ini

Deleting folder /home/indy/.android/avd/x86.avd



AVD 'x86' deleted.

Creating Android SDK

Warning: Observed package id 'emulator' in inconsistent location '/tmp/android_build/sdk/emulator_backup' (Expected '/tmp/android_build/sdk/emulator')

Loading local repository...                                                     
Warning: Observed package id 'emulator' in inconsistent location '/tmp/android_build/sdk/emulator_backup' (Expected '/tmp/android_build/sdk/emulator')

[=========                              ] 25% Loading local repository...       
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=============                          ] 34% Fetch remote repository...        
[================                       ] 42% Fetch remote repository...        
[================                       ] 42% Fetch remote repository...        
[=================                      ] 44% Fetch remote repository...        
[=================                      ] 45% Fetch remote repository...        
[==================                     ] 46% Fetch remote repository...        
[==================                     ] 46% Fetch remote repository...        
[==================                     ] 47% Fetch remote repository...        
[===================                    ] 48% Fetch remote repository...        
[===================                    ] 49% Fetch remote repository...        
[===================                    ] 49% Fetch remote repository...        
[====================                   ] 50% Fetch remote repository...        
[====================                   ] 51% Fetch remote repository...        
[====================                   ] 52% Fetch remote repository...        
[====================                   ] 52% Fetch remote repository...        
[=====================                  ] 53% Fetch remote repository...        
[=====================                  ] 54% Fetch remote repository...        
[=====================                  ] 55% Fetch remote repository...        
[======================                 ] 55% Fetch remote repository...        
[======================                 ] 56% Fetch remote repository...        
[======================                 ] 57% Fetch remote repository...        
[=======================                ] 58% Fetch remote repository...        
[=======================                ] 58% Fetch remote repository...        
                                                                                
Warning: File /home/indy/.android/repositories.cfg could not be loaded.

[=======================                ] 58% Fetch remote repository...        
[=======================                ] 58% Computing updates...              
[=============================          ] 75% Computing updates...              
[=============================          ] 75% Computing updates...              
[=======================================] 100% Computing updates...             
All SDK package licenses accepted.



Skipping sdkmanager activity

Creating android emulator

Loading local repository...                                                     
Warning: Observed package id 'emulator' in inconsistent location '/tmp/android_build/sdk/emulator_backup' (Expected '/tmp/android_build/sdk/emulator')

[=========                              ] 25% Loading local repository...       
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=======================================] 100% Fetch remote repository...       
Auto-selecting single ABI x86

Do you wish to create a custom hardware profile? [no] /home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/libnullpay

info: component 'rust-std' for target 'i686-linux-android' is up to date

/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/libnullpay /home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/libnullpay

statvfs('/home/indy/.android/avd/x86.avd/snapshots/default_boot/ram.img') failed: No such file or directory

 Downloading crates ...

  Downloaded rand v0.7.0

  Downloaded quote v1.0.2

  Downloaded env_logger v0.5.13

  Downloaded cfg-if v0.1.6

  Downloaded sha2 v0.8.0

  Downloaded serde_json v1.0.40

  Downloaded getrandom v0.1.1

  Downloaded quick-error v1.2.2

  Downloaded typenum v1.10.0

  Downloaded termcolor v1.0.4

  Downloaded atty v0.2.11

  Downloaded rand_core v0.5.0

  Downloaded regex v1.1.0

  Downloaded block-padding v0.1.4

  Downloaded opaque-debug v0.2.2

  Downloaded rand_chacha v0.2.0

  Downloaded itoa v0.4.3

  Downloaded utf8-ranges v1.0.2

  Downloaded thread_local v0.3.6

  Downloaded ryu v1.0.0

  Downloaded aho-corasick v0.6.9

  Downloaded regex-syntax v0.6.4

  Downloaded c2-chacha v0.2.2

  Downloaded autocfg v0.1.5

  Downloaded ucd-util v0.1.3

  Downloaded ppv-lite86 v0.2.5

   Compiling libc v0.2.66

   Compiling lazy_static v1.4.0

   Compiling typenum v1.10.0

   Compiling proc-macro2 v1.0.8

   Compiling memchr v2.3.0

   Compiling log v0.4.8

   Compiling byteorder v1.3.2

   Compiling autocfg v0.1.5

   Compiling cfg-if v0.1.6

   Compiling unicode-xid v0.2.0

   Compiling ppv-lite86 v0.2.5

   Compiling ucd-util v0.1.3

   Compiling ryu v1.0.0

### WARNING: could not find /usr/share/zoneinfo/ directory. unable to determine host timezone

   Compiling regex v1.1.0

   Compiling byte-tools v0.3.1

   Compiling serde v1.0.104

   Compiling syn v1.0.14

   Compiling utf8-ranges v1.0.2

   Compiling quick-error v1.2.2

   Compiling itoa v0.4.3

   Compiling termcolor v1.0.4

   Compiling fake-simd v0.1.2

   Compiling null-payment-method v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/libnullpay)

   Compiling android_log-sys v0.1.2

   Compiling opaque-debug v0.2.2

   Compiling thread_local v0.3.6

   Compiling c2-chacha v0.2.2

   Compiling rand_chacha v0.2.0

   Compiling regex-syntax v0.6.4

   Compiling block-padding v0.1.4

   Compiling humantime v1.3.0

### WARNING: could not find /usr/share/zoneinfo/ directory. unable to determine host timezone

   Compiling getrandom v0.1.1

   Compiling atty v0.2.11

   Compiling generic-array v0.12.3

   Compiling aho-corasick v0.6.9

   Compiling android_logger v0.5.3

   Compiling log-panics v2.0.0

   Compiling quote v1.0.2

   Compiling rand_core v0.5.0

   Compiling block-buffer v0.7.3

   Compiling digest v0.8.1

   Compiling serde_json v1.0.40

   Compiling sha2 v0.8.0

   Compiling env_logger v0.5.13

   Compiling rand v0.7.0

   Compiling serde_derive v1.0.104

    Finished release [optimized] target(s) in 3m 54s

 Downloading crates ...

  Downloaded failure v0.1.6

  Downloaded futures v0.1.25

  Downloaded pkg-config v0.3.14

  Downloaded dirs v1.0.4

  Downloaded num-traits v0.2.6

  Downloaded num-derive v0.2.3

  Downloaded failure_derive v0.1.6

  Downloaded quote v0.6.10

  Downloaded proc-macro2 v0.4.24

  Downloaded syn v0.15.23

  Downloaded rustc-demangle v0.1.11

  Downloaded backtrace-sys v0.1.26

   Compiling lazy_static v1.4.0

   Compiling cc v1.0.41

   Compiling proc-macro2 v0.4.24

   Compiling num-traits v0.2.6

   Compiling ucd-util v0.1.3

   Compiling unicode-xid v0.1.0

   Compiling utf8-ranges v1.0.2

   Compiling failure_derive v0.1.6

   Compiling pkg-config v0.3.14

   Compiling num-derive v0.2.3

   Compiling rustc-demangle v0.1.11

   Compiling futures v0.1.25

   Compiling memchr v2.3.0

   Compiling regex v1.1.0

   Compiling thread_local v0.3.6

   Compiling regex-syntax v0.6.4

   Compiling backtrace-sys v0.1.26

   Compiling dirs v1.0.4

   Compiling aho-corasick v0.6.9

   Compiling quote v0.6.10

   Compiling syn v0.15.23

   Compiling backtrace v0.3.11

   Compiling synstructure v0.12.3

   Compiling indy-sys v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/wrappers/rust/indy-sys)

   Compiling failure v0.1.6

   Compiling indy v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/wrappers/rust)

   Compiling null-payment-method v1.15.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/libnullpay)

warning: use of deprecated item 'indy::payments::build_get_payment_sources_request': please use `parse_get_payment_sources_with_from_response` instead

  --> tests/utils/payments.rs:23:5

   |

23 |     payments::build_get_payment_sources_request(wallet_handle, Some(submitter_did), payment_address).wait()

   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   |

   = note: `#[warn(deprecated)]` on by default



warning: use of deprecated item 'indy::payments::parse_get_payment_sources_response': please use `parse_get_payment_sources_with_from_response` instead

  --> tests/utils/payments.rs:28:5

   |

28 |     payments::parse_get_payment_sources_response(payment_method, resp_json).wait()

   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred

 --> tests/utils/plugin.rs:3:23

  |

3 | use std::sync::{Once, ONCE_INIT};

  |                       ^^^^^^^^^



warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred

 --> tests/utils/plugin.rs:6:55

  |

6 |         static ref CREATE_PAYMENT_METHOD_INIT: Once = ONCE_INIT;

  |                                                       ^^^^^^^^^ help: replace the use of the deprecated item: `Once::new()`



    Finished release [optimized] target(s) in 3m 54s

    Finished release [optimized] target(s) in 0.20s

/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2201/libnullpay

emulator is running

ls: /storage/emulated/0/: No such file or directory

waiting emulator FS

ls: /storage/emulated/0/: No such file or directory

waiting emulator FS

### WARNING: could not find /usr/share/zoneinfo/ directory. unable to determine host timezone

+ adb -e push /tmp/android_build/toolchains/linux/android-ndk-r20//sysroot/usr/lib/i686-linux-android/libc++_shared.so /data/local/tmp/libc++_shared.so

adb: error: cannot stat '/tmp/android_build/toolchains/linux/android-ndk-r20//sysroot/usr/lib/i686-linux-android/libc++_shared.so': No such file or directory

script returned exit code 1
```

**Comment by chaeso** [comment]
@Patrik-Stas / After changing incorrect path in libnullpay, libvcx, build looks successful

**Comment by vimmerru** [comment]
@chaeso 

Could you describe the problem you are trying to solve? Your script  changes that force x64 tools for all platforms don't look obvious for me.

**Pull request closed without merging**
