### PR TITLE
LibVCX iOS wrapper updates

### PR DESCRIPTION
**Pull request by airoasis**
Added APIs
* updateWebhookUrl
* errorCMessage
* connectionGetPwDid
* connectionGetTheirPwDid

Note: updateWebhookUrl is blocked by #2112

### CODE REVIEW

**Comment by Patrik-Stas** [comment]
@airoasis 
Failed with
```
   Compiling hyper v0.12.28

   Compiling hyper-tls v0.3.2

   Compiling reqwest v0.9.24

    Finished release [optimized + debuginfo] target(s) in 25m 18s

   Compiling libvcx v0.8.0 (/home/jenkins/workspace/indy-sdk_indy-sdk-ci_PR-2195/vcx/libvcx)

warning: use of deprecated item 'api::proof::vcx_get_proof': Use vcx_get_proof_msg() instead. This api is similar, but requires an extra parameter (connection_handle) which is unnecessary and unused in the internals.

   --> src/api/proof.rs:818:20

    |

818 |         assert_eq!(vcx_get_proof(cb.command_handle,

    |                    ^^^^^^^^^^^^^

    |

    = note: `#[warn(deprecated)]` on by default



warning: use of deprecated item 'api::proof::vcx_get_proof': Use vcx_get_proof_msg() instead. This api is similar, but requires an extra parameter (connection_handle) which is unnecessary and unused in the internals.

   --> src/api/proof.rs:833:20

    |

833 |         assert_eq!(vcx_get_proof(cb.command_handle,

    |                    ^^^^^^^^^^^^^



    Finished release [optimized + debuginfo] target(s) in 8m 15s

    Finished release [optimized + debuginfo] target(s) in 0.39s
```
And then CI/CD got stuck on having emulator still running. @Artemkaaas do you have rights to kill the pipeline run in jenkins?

**Comment by airoasis** [comment]
@Patrik-Stas Changes I made didn't cause these warnings. It was there since the commit belowhttps://github.com/hyperledger/indy-sdk/commit/4c4d4801b6d2d8d90a2205b59784cdb58144f694#diff-1a9a5af3e22f29835a04d611e63deddc

**Comment by Patrik-Stas** [comment]
@airoasis oh yeah you are right, it's just warning, and it's actually android test where it happened. I think it was unrelated issue with pipeline/executor. Those

**Comment by airoasis** [comment]
@jakubkoci, can you review this PR? #2112 is merged, so we can go ahead and merge this PR too :)

**Review by jovfer — APPROVED** [review]

**Pull request merged**
