### PR TITLE
[WIP] Update ubuntu-build.md to resolve issue 462

### PR DESCRIPTION
**Pull request by numical**
Added 'Troubleshooting' section with one way to fix [issue 462](https://github.com/hyperledger/indy-sdk/issues/462).

### CODE REVIEW

**Comment by numical** [comment]
Hi, I have added the DCO in the second commit but the checks still report it missing.

**Comment by jovfer** [comment]
Hi @numical 
DCO should present in all commits of PR
I suggest delete last commit, amend the first one with signature and force push to the branch of PR
```
git reset --hard HEAD~1
git commit --amend --signoff --no-edit
git push -f
```

**Comment by jovfer** [comment]
Also `git rebase --interactive` can be helpful in more complex cases (e.g. add DCO for multiply commits)

**Comment by esplinr** [comment]
@numical Do you need some more help signing the DCO?

We would like to accept this improvement, but need to meet the legal requirements for contribution.

**Comment by vimmerru** [comment]
On ubuntu we now suggest to build libsodium from sources. So information seems a bit outdated. Also no any feedback from requester for months.

**Pull request closed without merging**
