### PR TITLE
Sodiumoxide 0.2.1

### PR DESCRIPTION
**Pull request by AxelNennker**
New version of sodiumoxide up from 0.0.16 to 0.2.1

Had to unpin the libc version in wrappers/rust because of a conflict with libsodium-sys. Now using the same version as libsodium-sys

### CODE REVIEW

**Comment by AxelNennker** [comment]
Don't know why the build failed. `cargo build` on my Ubuntu 16.04 machine - native and in the libindy/ci/ubuntu.dockerfile container.

**Comment by AxelNennker** [comment]
Maybe first merge https://github.com/hyperledger/indy-sdk/pull/1585

**Comment by jovfer** [comment]
https://build.sovrin.org/job/indy-sdk/job/indy-sdk-ci/job/PR-1601/7/execution/node/155/log/

**Comment by AxelNennker** [comment]
This PR is superseded by https://github.com/hyperledger/indy-sdk/pull/1668

**Comment by AxelNennker** [comment]
This PR is superseded by https://github.com/hyperledger/indy-sdk/pull/1668

**Pull request closed without merging**
