### PR TITLE
[#2471] Failed to find OpenSSL development headers on MacOS

### PR DESCRIPTION
**Pull request by tdiesler**
signed-off-by: Thomas Diesler <tdiesler@redhat.com>

### CODE REVIEW

**Comment by WadeBarnes** [comment]
@tdiesler, I've fixed the issues causing the Jenkins builds to fail (https://github.com/hyperledger/indy-sdk/pull/2470).  If you rebase your PRs on the latest from the main branch the builds should work and we can get your PRs merged.

**Comment by tdiesler** [comment]
merci

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
It looks as though you have changes to ` samples/java/README.md` in this PR and in https://github.com/hyperledger/indy-sdk/pull/2469/files#diff-cf65c95c081ee03700a0c66bf9650daa8d1b1cc1dcc49897137a97f59040badb

Should the changes to that file be left out of this PR and left in the other?

**Comment by tdiesler** [comment]
I rebased - `samples/java/README.md` is not touched by this PR any more

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
