### PR TITLE
sodiumoxide 0.2.2 and remove sodium_static

### PR DESCRIPTION
**Pull request by AxelNennker**
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

sodiumoxide 0.2.2 uses libsodium-sys 0.2.3 which compiles libsodium-1.0.18 from source

### CODE REVIEW

**Comment by AxelNennker** [comment]
Where does the `cargo build --features "fatal_warnings sodium_static" ` come from that is failing this build. I do not see it in this branch libsodium-1.0.18

**Comment by jovfer** [comment]
It's Jenkins security policy: it uses Jenkinsfile.ci in case of PR from regular (not write permissioned) github user.
I manually triggered build on Jenkins with your updated .ci file https://build.sovrin.org/job/indy-sdk/job/indy-sdk-ci/view/change-requests/job/PR-1874/9/

**Comment by AxelNennker** [comment]
Strange openssl related bug while building this
https://build.sovrin.org/blue/organizations/jenkins/indy-sdk%2Findy-sdk-ci/detail/PR-1874/11/pipeline
More related to ubuntu18 than this PR, right?!

**Comment by AxelNennker** [comment]
It seems that on Windows libsodium is not found.
It should because the environment variables should be set when libsodium-sys is built.
https://github.com/sodiumoxide/sodiumoxide/tree/master/libsodium-sys
DEP_SODIUM_INCLUDE 
DEP_SODIUM_LIB

I have no idea how to fix this. The Ubuntu build seems to work that is libsodium-sys builds a static libsodium and sets the environment variables so that the next higher crate can find and use them.
Problem might be that libsodium is a dependency of two crates: zmq and indy
Maybe the order matters... I am guessing

**Comment by jovfer** [comment]
btw seems like there is some support around windows build from sources https://github.com/sodiumoxide/sodiumoxide/blob/master/libsodium-sys/build.rs#L384

hopefully I would be able to try to run native windows build on my personal PC next week

**Comment by AxelNennker** [comment]
Any news about the Windows build?

**Comment by AxelNennker** [comment]
Is it possible to tell Jenkins that this PR can use its own Jenkins files?

**Comment by AxelNennker** [comment]
Created new PR for sodiumoxide 0.2.5.
Closing this

**Pull request closed without merging**
