### PR TITLE
Align comments with recent data structure updates.

### PR DESCRIPTION
**Pull request by sklump**
Signed-off by: sklump <stephen.klump@becker-carroll.com>

### CODE REVIEW

**Comment by jovfer** [comment]
@sklump Is `stephen.klump@becker-carroll.com` email added to your GitHub account? Right now I don't understand the reason of DCO fail

**Comment by sklump** [comment]
Hello,


Address stephen.klump@becker-carroll.com must be present somewhere in GitHub as a secondary. I will remember for future submissions.


I spent years and years as a subversion administrator and when anything goes off the straight and narrow path in git, I still get myself in trouble. Sorry for all the clutter.


Regards,

Stephen



________________________________

**Comment by jovfer** [comment]
Moved to #537

**Comment by jovfer** [comment]
Moved to #537

**Pull request closed without merging**
